const mongoose = require('mongoose');

const EmployeeSchema = new mongoose.Schema({
    name:{type:String},
    father_name:{type:String},
    cnic:{type:String},
    address:{type:String},
    city:{type:String},
    cl:{type: Number,default: 5},
    sl:{type: Number,default: 5},
    el:{type: Number,default: 14},    
    email:{type:String},
    telephone:{type:String},
    mobile:{type:String},
    ext:{type:String},
    ntn:{type:String},
    dl_number:{type:String},
    dl_expiry:{type:String},
    pp_number:{type:String},
    pp_expiry:{type:String},
    bg:{type:String},
    doi:{type:String},
    section:{type:String},
    e_code:{type:String},
    a_hr:{type:String},
    a_lunch:{type:String},
    a_mobile:{type:String},
    a_transport:{type:String},
    d_tax:{type:String},
    d_retention:{type:String},
    d_sales:{type:String},
    a_package:{type:String},
    a_hpw:{type:String},
    p_e:{type:String},
    reference:{type:String},
    dob:{type:String},
    marital_status:{type:String},
    education:{type:Object,default:{}},
    experiences:{type:Object,default:{}},
    basic_salary:{type:Number,default:0},
    designation:{type:String},
    active:{type:Boolean,default:true},
    w_b:{type:Boolean,default:false},
    dept:{type:String},
    division:{type:String},
    picture:{type:String},
    username:{type:String},
    password:{type:String},
    previledge:{type:Array,default:[]}
});
module.exports = mongoose.model('employees',EmployeeSchema);